GOTY_WINNERS = [
{"Game":"Diablo","Developer":"Blizzard Noth","Year":1996},
{"Game":"Total Annihilation","Developer":"Cavedog Ent.","Year":1997},
{"Game":"The Legend of Zelda: Ocarina of Time","Developer":"Nintendo EAD","Year":1998},
{"Game":"SoulCalibur","Developer":"Namco","Year":1999},
{"Game":"Chrono Cross","Developer":"Square Co.","Year":2000},
{"Game":"Grand Theft Auto III","Developer":"Rockstar North","Year":2001},
{"Game":"Metroid Prime","Developer":"Retro Studios, Nintendo","Year":2002},
{"Game":"The Legend of Zelda: The Wind Waker","Developer":"Nintendo","Year":2003},
{"Game":"World of Warcraft","Developer":"Blizzard Entertainment","Year":2004},
{"Game":"Resident Evil 4","Developer":"Capcom","Year":2005},
{"Game":"Gears of War","Developer":"Epic Games","Year":2006},
{"Game":"Super Mario Galaxy","Developer":"Nintendo","Year":2007},
{"Game":"Metal Gear Solid 4: Guns of the Patriots","Developer":"Kojima Productions","Year":2008},
{"Game":"Demon's Souls","Developer":"FromSoftware","Year":2009},
{"Game":"Red Dead Redemption","Developer":"Rockstar Games","Year":2010},
{"Game":"The Elder Scrolls V: Skyrim","Developer":"Bethesda Game Studios","Year":2011},
{"Game":"Journey","Developer":"Thatgamecompany","Year":2012},
{"Game":"The Legend of Zelda: A Link Between Worlds","Developer":"Nintendo","Year":2013},
{"Game":"Middle-earth: Shadow of Mordor","Developer":"Monolith Productions","Year":2014},
{"Game":"The Witcher 3: Wild Hunt","Developer":"CD Projekt RED","Year":2015}];
